export const TIMING = {
	TYPE_DELAY_MIN: 22,
	TYPE_DELAY_MAX: 55,
	TYPE_PUNC_PAUSE: 140,
	REVEAL_DELAY_MIN: 80,
	REVEAL_DELAY_MAX: 120,
	IDLE_HEADER_REVEAL_MS: 960,
	SCORE_ANIMATE_MS: 720,
} as const;
