import type { Round } from "./types.ts";

function attaches(word: string): boolean {
	return /^[^\w]+$/u.test(word) || word.startsWith("'");
}

function r(word: string) {
	return { kind: "reveal" as const, word, leading_space: !attaches(word) };
}

function c(correct: string, d1: string, d2: string) {
	return {
		kind: "choice" as const,
		correct,
		distractors: [d1, d2] as [string, string],
		leading_space: !attaches(correct),
	};
}

export const mockRounds: Round[] = [
	{
		id: "round-1",
		prompt: "Explain why the sky is blue.",
		tokens: [
			r("The"),
			r("sky"),
			c("appears", "becomes", "stays"),
			r("blue"),
			r("because"),
			r("of"),
			r("a"),
			c("phenomenon", "process", "reaction"),
			r("called"),
			c("Rayleigh", "Newton", "Doppler"),
			c("scattering", "reflection", "absorption"),
			r("."),
			r("When"),
			c("sunlight", "moonlight", "starlight"),
			r("enters"),
			r("the"),
			c("atmosphere", "stratosphere", "ionosphere"),
			r(","),
			r("it"),
			c("collides", "merges", "aligns"),
			r("with"),
			c("molecules", "atoms", "particles"),
			r("of"),
			r("nitrogen"),
			r("and"),
			c("oxygen", "carbon", "helium"),
			r("."),
			r("Shorter"),
			c("wavelengths", "frequencies", "amplitudes"),
			r("of"),
			r("light"),
			r(","),
			r("like"),
			c("blue", "red", "green"),
			r("and"),
			r("violet"),
			r(","),
			r("are"),
			c("scattered", "absorbed", "reflected"),
			r("more"),
			r("than"),
			c("longer", "shorter", "weaker"),
			r("wavelengths"),
			r("."),
			r("This"),
			c("scattered", "filtered", "refracted"),
			r("blue"),
			r("light"),
			r("reaches"),
			r("our"),
			c("eyes", "brain", "sensors"),
			r("from"),
			r("all"),
			c("directions", "angles", "sides"),
			r(","),
			r("making"),
			r("the"),
			r("sky"),
			r("appear"),
			r("blue"),
			r("."),
		],
	},
	{
		id: "round-2",
		prompt: "What is the difference between a list and a tuple in Python?",
		tokens: [
			r("In"),
			r("Python"),
			r(","),
			r("a"),
			c("list", "tuple", "set"),
			r("is"),
			c("mutable", "immutable", "static"),
			r(","),
			r("meaning"),
			r("you"),
			r("can"),
			c("modify", "access", "delete"),
			r("its"),
			c("elements", "values", "contents"),
			r("after"),
			c("creation", "initialization", "declaration"),
			r("."),
			r("A"),
			c("tuple", "list", "dict"),
			r(","),
			r("on"),
			r("the"),
			r("other"),
			r("hand"),
			r(","),
			r("is"),
			c("immutable", "mutable", "flexible"),
			r("—"),
			r("once"),
			c("created", "defined", "set"),
			r(","),
			r("its"),
			r("contents"),
			c("cannot", "should", "will"),
			r("be"),
			c("changed", "accessed", "copied"),
			r("."),
			r("Lists"),
			r("use"),
			c("square", "round", "curly"),
			c("brackets", "braces", "parentheses"),
			r(","),
			r("while"),
			r("tuples"),
			r("use"),
			c("parentheses", "brackets", "braces"),
			r("."),
			r("Tuples"),
			r("are"),
			c("generally", "always", "never"),
			c("faster", "slower", "safer"),
			r("and"),
			r("use"),
			r("less"),
			c("memory", "storage", "bandwidth"),
			r("than"),
			r("lists"),
			r("."),
		],
	},
	{
		id: "round-3",
		prompt: "How does photosynthesis work?",
		tokens: [
			r("Photosynthesis"),
			r("is"),
			r("the"),
			c("process", "method", "cycle"),
			r("by"),
			r("which"),
			c("plants", "animals", "fungi"),
			c("convert", "transform", "absorb"),
			c("sunlight", "heat", "water"),
			r("into"),
			c("chemical", "thermal", "kinetic"),
			c("energy", "force", "power"),
			r("."),
			r("It"),
			c("occurs", "happens", "begins"),
			r("primarily"),
			r("in"),
			r("the"),
			c("leaves", "roots", "stems"),
			r(","),
			r("inside"),
			c("organelles", "cells", "membranes"),
			r("called"),
			c("chloroplasts", "mitochondria", "ribosomes"),
			r("."),
			r("These"),
			c("contain", "produce", "release"),
			r("a"),
			r("green"),
			c("pigment", "chemical", "substance"),
			r("called"),
			c("chlorophyll", "carotene", "xanthophyll"),
			r(","),
			r("which"),
			c("absorbs", "reflects", "emits"),
			r("light"),
			r("."),
			r("The"),
			r("plant"),
			c("takes", "pulls", "draws"),
			r("in"),
			c("carbon", "nitrogen", "sulfur"),
			r("dioxide"),
			r("from"),
			r("the"),
			r("air"),
			r("and"),
			c("water", "minerals", "nutrients"),
			r("from"),
			r("the"),
			c("soil", "air", "roots"),
			r(","),
			r("then"),
			c("produces", "releases", "creates"),
			c("glucose", "starch", "sucrose"),
			r("and"),
			c("oxygen", "nitrogen", "hydrogen"),
			r("."),
		],
	},
	{
		id: "round-4",
		prompt: "Why do we dream?",
		tokens: [
			r("The"),
			c("exact", "true", "real"),
			c("reason", "cause", "purpose"),
			r("we"),
			r("dream"),
			r("is"),
			r("still"),
			c("debated", "unknown", "controversial"),
			r("among"),
			c("scientists", "researchers", "experts"),
			r(","),
			r("but"),
			r("several"),
			c("theories", "hypotheses", "ideas"),
			c("exist", "persist", "compete"),
			r("."),
			r("One"),
			c("prominent", "popular", "leading"),
			r("theory"),
			c("suggests", "argues", "proposes"),
			r("that"),
			r("dreams"),
			r("help"),
			r("our"),
			c("brains", "minds", "neurons"),
			c("process", "organize", "filter"),
			r("and"),
			c("consolidate", "store", "archive"),
			c("memories", "experiences", "information"),
			r("from"),
			r("the"),
			r("day"),
			r("."),
			r("Another"),
			r("theory"),
			c("proposes", "claims", "states"),
			r("that"),
			c("dreaming", "sleeping", "resting"),
			r("serves"),
			r("as"),
			r("a"),
			c("rehearsal", "simulation", "practice"),
			r("for"),
			c("threatening", "dangerous", "stressful"),
			c("scenarios", "situations", "events"),
			r(","),
			r("helping"),
			r("us"),
			c("prepare", "train", "adapt"),
			r("for"),
			r("real-life"),
			c("challenges", "dangers", "problems"),
			r("."),
		],
	},
	{
		id: "round-5",
		prompt: "Explain how a neural network learns.",
		tokens: [
			r("A"),
			r("neural"),
			c("network", "system", "model"),
			r("learns"),
			r("by"),
			c("adjusting", "changing", "updating"),
			r("the"),
			c("weights", "values", "parameters"),
			r("of"),
			r("its"),
			c("connections", "layers", "nodes"),
			r("based"),
			r("on"),
			c("errors", "mistakes", "differences"),
			r("in"),
			r("its"),
			c("predictions", "outputs", "results"),
			r("."),
			r("First"),
			r(","),
			r("input"),
			c("data", "signals", "values"),
			r("is"),
			c("fed", "passed", "sent"),
			r("through"),
			r("the"),
			r("network"),
			r(","),
			r("producing"),
			r("an"),
			c("output", "answer", "result"),
			r("."),
			r("This"),
			r("output"),
			r("is"),
			c("compared", "matched", "checked"),
			r("to"),
			r("the"),
			c("expected", "correct", "target"),
			c("answer", "value", "result"),
			r(","),
			r("and"),
			r("the"),
			c("difference", "gap", "error"),
			r("is"),
			c("calculated", "measured", "computed"),
			r("."),
			r("Then"),
			r(","),
			r("through"),
			r("a"),
			r("process"),
			r("called"),
			c("backpropagation", "feedforward", "gradient"),
			r(","),
			r("the"),
			r("network"),
			c("adjusts", "updates", "tunes"),
			r("its"),
			r("weights"),
			r("to"),
			c("minimize", "reduce", "lower"),
			r("future"),
			c("errors", "loss", "mistakes"),
			r("."),
		],
	},
	{
		id: "round-6",
		prompt: "What causes ocean tides?",
		tokens: [
			r("Ocean"),
			c("tides", "waves", "currents"),
			r("are"),
			c("primarily", "mainly", "mostly"),
			c("caused", "driven", "created"),
			r("by"),
			r("the"),
			c("gravitational", "magnetic", "rotational"),
			c("pull", "force", "field"),
			r("of"),
			r("the"),
			c("Moon", "Sun", "Earth"),
			r("."),
			r("The"),
			r("Moon"),
			r("'s"),
			c("gravity", "mass", "orbit"),
			c("attracts", "pulls", "draws"),
			r("the"),
			r("water"),
			r("on"),
			r("the"),
			c("nearest", "closest", "facing"),
			r("side"),
			r("of"),
			r("Earth"),
			r(","),
			r("creating"),
			r("a"),
			c("bulge", "wave", "rise"),
			r("of"),
			r("high"),
			c("tide", "water", "pressure"),
			r("."),
			r("A"),
			c("second", "another", "matching"),
			r("bulge"),
			c("forms", "appears", "occurs"),
			r("on"),
			r("the"),
			c("opposite", "far", "other"),
			r("side"),
			r("due"),
			r("to"),
			c("inertia", "momentum", "centrifugal"),
			c("forces", "effects", "energy"),
			r("."),
			r("As"),
			r("Earth"),
			c("rotates", "spins", "turns"),
			r(","),
			c("coastlines", "shores", "beaches"),
			c("experience", "undergo", "see"),
			r("two"),
			r("high"),
			r("tides"),
			r("and"),
			r("two"),
			r("low"),
			r("tides"),
			c("daily", "each", "per"),
			r("."),
		],
	},
	{
		id: "round-7",
		prompt: "How does encryption keep data safe?",
		tokens: [
			r("Encryption"),
			c("protects", "secures", "shields"),
			r("data"),
			r("by"),
			c("converting", "transforming", "encoding"),
			r("it"),
			r("into"),
			r("an"),
			c("unreadable", "scrambled", "encrypted"),
			c("format", "form", "code"),
			r("using"),
			r("a"),
			c("mathematical", "complex", "cryptographic"),
			c("algorithm", "function", "cipher"),
			r("."),
			r("Only"),
			c("someone", "users", "parties"),
			r("with"),
			r("the"),
			c("correct", "matching", "proper"),
			c("key", "password", "token"),
			r("can"),
			c("decrypt", "decode", "unlock"),
			r("and"),
			r("read"),
			r("the"),
			c("original", "actual", "raw"),
			r("data"),
			r("."),
			r("There"),
			r("are"),
			r("two"),
			c("main", "primary", "common"),
			c("types", "forms", "methods"),
			r(":"),
			c("symmetric", "private", "shared"),
			r("encryption"),
			r(","),
			r("where"),
			r("the"),
			r("same"),
			r("key"),
			c("encrypts", "locks", "protects"),
			r("and"),
			c("decrypts", "unlocks", "reveals"),
			r(","),
			r("and"),
			c("asymmetric", "public", "dual"),
			r("encryption"),
			r(","),
			r("which"),
			r("uses"),
			r("a"),
			c("pair", "set", "combination"),
			r("of"),
			c("keys", "tokens", "codes"),
			r("."),
		],
	},
];
